volumes:
  nginx_proxy_data:
    external: true
  nginx_proxy_letsencrypt:
    external: true

services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.22.0.3
      logistics-backoffice-api_poled-net:
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
       - nginx_proxy_data:/data
       - nginx_proxy_letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: nginx_network
  logistics-backoffice-api_poled-net:
    external: true