services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      default:
        ipv4_address: 172.22.0.5
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"

networks:
  default:
    external: true
    name: nginx_network
